/var/log/dcnet/*.log {
    # rotate when log reaches 10k
    size 10k
    # keep 30 log files
    rotate 30
    compress
    # Do not rotate if empty
    notifempty

    delaycompress
    missingok
    copytruncate
}
